CREATE DATABASE IF NOT EXISTS `frani`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_520_ci;

USE `frani`;

CREATE TABLE IF NOT EXISTS `categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `agregado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_categorias_nombre` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE IF NOT EXISTS `productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) DEFAULT NULL,
  `descripcion` TEXT DEFAULT NULL,
  `costo` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `stock` INT NULL DEFAULT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  `agregado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_productos_id_categoria` (`id_categoria`),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`id_categoria`) REFERENCES `categorias` (`id`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE IF NOT EXISTS `facturas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `efectivo` DECIMAL(10,2) DEFAULT NULL,
  `transferencia` DECIMAL(10,2) DEFAULT NULL,
  `deuda` DECIMAL(10,2) DEFAULT NULL,
  `detalle` TEXT NOT NULL,
  `observaciones` TEXT DEFAULT NULL,
  `agregado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE IF NOT EXISTS `clientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `foto` VARCHAR(255) DEFAULT NULL,
  `telefono` VARCHAR(50) DEFAULT NULL,
  `agregado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `foto` VARCHAR(255) DEFAULT NULL,
  `correo` VARCHAR(200) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) DEFAULT NULL,
  `ingreso` TIMESTAMP NULL DEFAULT NULL,
  `editado` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_usuarios_correo` (`correo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

INSERT INTO `categorias` (`nombre`)
SELECT 'General'
WHERE NOT EXISTS (
  SELECT 1
  FROM `categorias`
  WHERE `nombre` = 'General'
);

INSERT IGNORE INTO `usuarios` (`nombre`, `correo`, `clave`)
VALUES ('admin', 'pabloruiz1980@gmail.com', '$2y$12$emBPsJNMpsTuqm7ww9pUFuMFC5G/XwE3r/JmDndscLZ5WC8wsJGau');
